extends: existence
message: "Format functions and function blocks as markdown code: `%s`."
ignorecase: false
level: error
nonword: true
tokens:
  - 'FB_\w+'
  - 'F_\w+'
  - 'MC_\w+'
  - 'ST_\w+'
  - 'Tc[23]_\w+'
